openapi: 3.0.3
info:
  title: Catalog Search API
  description: API for searching catalog items with rate limiting support and creating purchase requisitions
  version: 1.0.0
servers:
  - url: https://mockoon.flunq.io/m1/1044590-1031883-default
    description: Production server
paths:
  /requisition/create:
    post:
      summary: Create a purchase requisition
      description: Create a new purchase requisition with specified items and delivery details
      operationId: createRequisition
      tags:
        - Requisition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequisitionRequest'
            example:
              requester:
                id: "u-10023"
                name: "Jane Doe"
                email: "jane.doe@company.com"
              currency: "USD"
              neededBy: "2025-10-15"
              shipTo:
                name: "Main Warehouse"
                addressLine1: "123 Example St"
                city: "Austin"
                state: "TX"
                postalCode: "78701"
                country: "US"
              items:
                - lineNo: 1
                  catalogId: "CAT-000123"
                  description: "USB-C Hub (6-port)"
                  quantity: 2
                  uom: "EA"
                  unitPrice: 49.99
                  currency: "USD"
                  supplier:
                    id: "SUP-1001"
                    name: "Acme Supplies"
                  commodityCode: "43211601"
              justification: "New hires"
      responses:
        '201':
          description: Requisition created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequisitionResponse'
        '400':
          description: Bad request - invalid requisition data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    RequisitionRequest:
      type: object
      required:
        - requester
        - currency
        - neededBy
        - shipTo
        - items
        - justification
      properties:
        requester:
          $ref: '#/components/schemas/Requester'
        currency:
          type: string
          description: Currency code for the requisition
          example: "USD"
        neededBy:
          type: string
          format: date
          description: Date when items are needed (YYYY-MM-DD)
          example: "2025-10-15"
        shipTo:
          $ref: '#/components/schemas/ShippingAddress'
        items:
          type: array
          items:
            $ref: '#/components/schemas/RequisitionItem'
          minItems: 1
        justification:
          type: string
          description: Business justification for the requisition
          example: "New hires"

    RequisitionResponse:
      type: object
      required:
        - requisitionId
        - status
        - totalAmount
        - createdAt
      properties:
        requisitionId:
          type: string
          description: Unique identifier for the created requisition
          example: "REQ-2025-001234"
        status:
          type: string
          description: Current status of the requisition
          enum: ["DRAFT", "SUBMITTED", "APPROVED", "REJECTED", "CANCELLED"]
          example: "SUBMITTED"
        totalAmount:
          type: number
          format: double
          description: Total amount of the requisition
          example: 99.98
        currency:
          type: string
          description: Currency of the total amount
          example: "USD"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when requisition was created
          example: "2025-09-25T14:30:00.000Z"
        requester:
          $ref: '#/components/schemas/Requester'
        neededBy:
          type: string
          format: date
          example: "2025-10-15"
        shipTo:
          $ref: '#/components/schemas/ShippingAddress'
        items:
          type: array
          items:
            $ref: '#/components/schemas/RequisitionItem'

    Requester:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          description: Unique identifier for the requester
          example: "u-10023"
        name:
          type: string
          description: Full name of the requester
          example: "Jane Doe"
        email:
          type: string
          format: email
          description: Email address of the requester
          example: "jane.doe@company.com"

    ShippingAddress:
      type: object
      required:
        - name
        - addressLine1
        - city
        - country
      properties:
        name:
          type: string
          description: Name of the shipping location
          example: "Main Warehouse"
        addressLine1:
          type: string
          description: Primary address line
          example: "123 Example St"
        addressLine2:
          type: string
          description: Secondary address line (optional)
          example: "Suite 100"
        city:
          type: string
          description: City name
          example: "Austin"
        state:
          type: string
          description: State or province code
          example: "TX"
        postalCode:
          type: string
          description: Postal or ZIP code
          example: "78701"
        country:
          type: string
          description: Country code (ISO 3166-1 alpha-2)
          example: "US"

    RequisitionItem:
      type: object
      required:
        - lineNo
        - catalogId
        - description
        - quantity
        - uom
        - unitPrice
        - currency
        - supplier
      properties:
        lineNo:
          type: integer
          description: Line number for ordering
          minimum: 1
          example: 1
        catalogId:
          type: string
          description: Reference to catalog item ID
          example: "CAT-000123"
        description:
          type: string
          description: Description of the item
          example: "USB-C Hub (6-port)"
        quantity:
          type: integer
          description: Quantity requested
          minimum: 1
          example: 2
        uom:
          type: string
          description: Unit of measure
          example: "EA"
        unitPrice:
          type: number
          format: double
          description: Unit price of the item
          minimum: 0
          example: 49.99
        currency:
          type: string
          description: Currency code for the unit price
          example: "USD"
        supplier:
          $ref: '#/components/schemas/Supplier'
        commodityCode:
          type: string
          description: UNSPSC commodity code (optional)
          example: "43211601"

    Supplier:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: Unique identifier for the supplier
          example: "SUP-1001"
        name:
          type: string
          description: Name of the supplier
          example: "Acme Supplies"
        
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "INVALID_REQUEST"
        message:
          type: string
          example: "Search term is required"
    
    RateLimitError:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              example: 429
            message:
              type: string
              example: "Too Many Requests - Rate limit exceeded"
            details:
              type: string
              example: "Please retry after 5 seconds"
            timestamp:
              type: string
              format: date-time
              example: "2024-01-15T10:30:00.000Z"
            retryAfter:
              type: integer
              description: Seconds to wait before retrying
              example: 5
            attemptNumber:
              type: integer
              description: Current attempt number (for testing)
              example: 1
